//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bitacora_API.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registros
    {
        public string id { get; set; }
        public Nullable<int> kilometraje { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
    }
}
